export default {
    data: {
        "deparment": [
            {
                "deparment": "ANTIOQUIA",
                "departamento_c": "5"
            },
            { "deparment": "ATLANTICO", "departamento_c": "8" },
            { "deparment": "BOGOTA", "departamento_c": "11" },
            { "deparment": "BOLIVAR", "departamento_c": "13" },
            { "deparment": "BOYACA", "departamento_c": "15" },
            { "deparment": "CALDAS", "departamento_c": "17" },
            { "deparment": "CAQUETA", "departamento_c": "18" },
            { "deparment": "CAUCA", "departamento_c": "19" },
            { "deparment": "CESAR", "departamento_c": "20" },
            { "deparment": "CORDOBA", "departamento_c": "23" },
            { "deparment": "CUNDINAMARCA", "departamento_c": "25" },
            { "deparment": "CHOCO", "departamento_c": "27" },
            { "deparment": "HUILA", "departamento_c": "41" },
            { "deparment": "LA GUAJIRA", "departamento_c": "44" },
            { "deparment": "MAGDALENA", "departamento_c": "47" },
            { "deparment": "META", "departamento_c": "50" },
            { "deparment": "NARIÑO", "departamento_c": "52" },
            { "deparment": "N. DE SANTANDER", "departamento_c": "54" },
            { "deparment": "QUINDIO", "departamento_c": "63" },
            { "deparment": "RISARALDA", "departamento_c": "66" },
            { "deparment": "SANTANDER", "departamento_c": "68" },
            { "deparment": "SUCRE", "departamento_c": "70" },
            { "deparment": "TOLIMA", "departamento_c": "73" },
            { "deparment": "VALLE DEL CAUCA", "departamento_c": "76" },
            { "deparment": "ARAUCA", "departamento_c": "81" },
            { "deparment": "CASANARE", "departamento_c": "85" },
            { "deparment": "PUTUMAYO", "departamento_c": "86" },
            { "deparment": "SAN ANDRES", "departamento_c": "88" },
            { "deparment": "AMAZONAS", "departamento_c": "91" },
            { "deparment": "GUAINIA", "departamento_c": "94" },
            { "deparment": "GUAVIARE", "departamento_c": "95" },
            { "deparment": "VAUPES", "departamento_c": "97" },
            { "deparment": "VICHADA", "departamento_c": "99" },
        ],
        "genero_customer":{
            "F":"Femenino",
            "M":"MAsculino"
        },
        "deparment_customer": {
            "5": "ANTIOQUIA",
            "8": "ATLANTICO",
            "11": "BOGOTA",
            "13": "BOLIVAR",
            "15": "BOYACA",
            "17": "CALDAS",
            "18": "CAQUETA",
            "19": "CAUCA",
            "20": "CESAR",
            "23": "CORDOBA",
            "25": "CUNDINAMARCA",
            "27": "CHOCO",
            "41": "HUILA",
            "44": "LA GUAJIRA",
            "47": "MAGDALENA",
            "50": "META",
            "52": "NARIÑO",
            "54": "N. DE SANTANDER",
            "63": "QUINDIO",
            "66": "RISARALDA",
            "68": "SANTANDER",
            "70": "SUCRE",
            "73": "TOLIMA",
            "76": "VALLE DEL CAUCA",
            "81": "ARAUCA",
            "85": "CASANARE",
            "86": "PUTUMAYO",
            "88": "SAN ANDRES",
            "91": "AMAZONAS",
            "94": "GUAINIA",
            "95": "GUAVIARE",
            "97": "VAUPES",
            "99": "VICHADA"
        },
        "cities_customer": {
            '5_001': 'MEDELLIN',
            '5_002': 'ABEJORRAL',
            '5_004': 'ABRIAQUI',
            '5_021': 'ALEJANDRIA',
            '5_030': 'AMAGA',
            '5_031': 'AMALFI',
            '5_034': 'ANDES',
            '5_036': 'ANGELOPOLIS',
            '5_038': 'ANGOSTURA',
            '5_040': 'ANORI',
            '5_042': 'SANTAFE DE ANTIOQUIA',
            '5_044': 'ANZA',
            '5_045': 'APARTADO',
            '5_051': 'ARBOLETES',
            '5_055': 'ARGELIA',
            '5_059': 'ARMENIA',
            '5_079': 'BARBOSA',
            '5_086': 'BELMIRA',
            '5_088': 'BELLO',
            '5_091': 'BETANIA',
            '5_093': 'BETULIA',
            '5_101': 'CIUDAD BOLIVAR',
            '5_107': 'BRICEÑO',
            '5_113': 'BURITICA',
            '5_120': 'CACERES',
            '5_125': 'CAICEDO',
            '5_129': 'CALDAS',
            '5_134': 'CAMPAMENTO',
            '5_138': 'CAÑASGORDAS',
            '5_142': 'CARACOLI',
            '5_145': 'CARAMANTA',
            '5_147': 'CAREPA',
            '5_148': 'EL CARMEN DE VIBORAL',
            '5_150': 'CAROLINA',
            '5_154': 'CAUCASIA',
            '5_172': 'CHIGORODO',
            '5_190': 'CISNEROS',
            '5_197': 'COCORNA',
            '5_206': 'CONCEPCION',
            '5_209': 'CONCORDIA',
            '5_212': 'COPACABANA',
            '5_234': 'DABEIBA',
            '5_237': 'DON MATIAS',
            '5_240': 'EBEJICO',
            '5_250': 'EL BAGRE',
            '5_264': 'ENTRERRIOS',
            '5_266': 'ENVIGADO',
            '5_282': 'FREDONIA',
            '5_284': 'FRONTINO',
            '5_306': 'GIRALDO',
            '5_308': 'GIRARDOTA',
            '5_310': 'GOMEZ PLATA',
            '5_313': 'GRANADA',
            '5_315': 'GUADALUPE',
            '5_318': 'GUARNE',
            '5_321': 'GUATAPE',
            '5_347': 'HELICONIA',
            '5_353': 'HISPANIA',
            '5_360': 'ITAGUI',
            '5_361': 'ITUANGO',
            '5_364': 'JARDIN',
            '5_368': 'JERICO',
            '5_376': 'LA CEJA',
            '5_380': 'LA ESTRELLA',
            '5_390': 'LA PINTADA',
            '5_400': 'LA UNION',
            '5_411': 'LIBORINA',
            '5_425': 'MACEO',
            '5_440': 'MARINILLA',
            '5_467': 'MONTEBELLO',
            '5_475': 'MURINDO',
            '5_480': 'MUTATA',
            '5_483': 'NARIÑO',
            '5_490': 'NECOCLI',
            '5_495': 'NECHI',
            '5_501': 'OLAYA',
            '5_541': 'PEÐOL',
            '5_543': 'PEQUE',
            '5_576': 'PUEBLORRICO',
            '5_579': 'PUERTO BERRIO',
            '5_585': 'PUERTO NARE',
            '5_591': 'PUERTO TRIUNFO',
            '5_604': 'REMEDIOS',
            '5_607': 'RETIRO',
            '5_615': 'RIONEGRO',
            '5_628': 'SABANALARGA',
            '5_631': 'SABANETA',
            '5_642': 'SALGAR',
            '5_647': 'SAN ANDRES DE CUERQUIA',
            '5_649': 'SAN CARLOS',
            '5_652': 'SAN FRANCISCO',
            '5_656': 'SAN JERONIMO',
            '5_658': 'SAN JOSE DE LA MONTAÑA',
            '5_659': 'SAN JUAN DE URABA',
            '5_660': 'SAN LUIS',
            '5_664': 'SAN PEDRO',
            '5_665': 'SAN PEDRO DE URABA',
            '5_667': 'SAN RAFAEL',
            '5_670': 'SAN ROQUE',
            '5_674': 'SAN VICENTE',
            '5_679': 'SANTA BARBARA',
            '5_686': 'SANTA ROSA DE OSOS',
            '5_690': 'SANTO DOMINGO',
            '5_697': 'EL SANTUARIO',
            '5_736': 'SEGOVIA',
            '5_756': 'SONSON',
            '5_761': 'SOPETRAN',
            '5_789': 'TAMESIS',
            '5_790': 'TARAZA',
            '5_792': 'TARSO',
            '5_809': 'TITIRIBI',
            '5_819': 'TOLEDO',
            '5_837': 'TURBO',
            '5_842': 'URAMITA',
            '5_847': 'URRAO',
            '5_854': 'VALDIVIA',
            '5_856': 'VALPARAISO',
            '5_858': 'VEGACHI',
            '5_861': 'VENECIA',
            '5_873': 'VIGIA DEL FUERTE',
            '5_885': 'YALI',
            '5_887': 'YARUMAL',
            '5_890': 'YOLOMBO',
            '5_893': 'YONDO',
            '5_895': 'ZARAGOZA',
            '8_001': 'BARRANQUILLA',
            '8_078': 'BARANOA',
            '8_137': 'CAMPO DE LA CRUZ',
            '8_141': 'CANDELARIA',
            '8_296': 'GALAPA',
            '8_372': 'JUAN DE ACOSTA',
            '8_421': 'LURUACO',
            '8_433': 'MALAMBO',
            '8_436': 'MANATI',
            '8_520': 'PALMAR DE VARELA',
            '8_549': 'PIOJO',
            '8_558': 'POLONUEVO',
            '8_560': 'PONEDERA',
            '8_573': 'PUERTO COLOMBIA',
            '8_606': 'REPELON',
            '8_634': 'SABANAGRANDE',
            '8_638': 'SABANALARGA',
            '8_675': 'SANTA LUCIA',
            '8_685': 'SANTO TOMAS',
            '8_758': 'SOLEDAD',
            '8_770': 'SUAN',
            '8_832': 'TUBARA',
            '8_849': 'USIACURI',
            '11_001': 'BOGOTA, D.C.',
            '13_001': 'CARTAGENA',
            '13_006': 'ACHI',
            '13_030': 'ALTOS DEL ROSARIO',
            '13_042': 'ARENAL',
            '13_052': 'ARJONA',
            '13_062': 'ARROYOHONDO',
            '13_074': 'BARRANCO DE LOBA',
            '13_140': 'CALAMAR',
            '13_160': 'CANTAGALLO',
            '13_188': 'CICUCO',
            '13_212': 'CORDOBA',
            '13_222': 'CLEMENCIA',
            '13_244': 'EL CARMEN DE BOLIVAR',
            '13_248': 'EL GUAMO',
            '13_268': 'EL PEÑON',
            '13_300': 'HATILLO DE LOBA',
            '13_430': 'MAGANGUE',
            '13_433': 'MAHATES',
            '13_440': 'MARGARITA',
            '13_442': 'MARIA LA BAJA',
            '13_458': 'MONTECRISTO',
            '13_468': 'MOMPOS',
            '13_490': 'NOROSI',
            '13_473': 'MORALES',
            '13_549': 'PINILLOS',
            '13_580': 'REGIDOR',
            '13_600': 'RIO VIEJO',
            '13_620': 'SAN CRISTOBAL',
            '13_647': 'SAN ESTANISLAO',
            '13_650': 'SAN FERNANDO',
            '13_654': 'SAN JACINTO',
            '13_655': 'SAN JACINTO DEL CAUCA',
            '13_657': 'SAN JUAN NEPOMUCENO',
            '13_667': 'SAN MARTIN DE LOBA',
            '13_670': 'SAN PABLO',
            '13_673': 'SANTA CATALINA',
            '13_683': 'SANTA ROSA',
            '13_688': 'SANTA ROSA DEL SUR',
            '13_744': 'SIMITI',
            '13_760': 'SOPLAVIENTO',
            '13_780': 'TALAIGUA NUEVO',
            '13_810': 'TIQUISIO',
            '13_836': 'TURBACO',
            '13_838': 'TURBANA',
            '13_873': 'VILLANUEVA',
            '13_894': 'ZAMBRANO',
            '15_001': 'TUNJA',
            '15_022': 'ALMEIDA',
            '15_047': 'AQUITANIA',
            '15_051': 'ARCABUCO',
            '15_087': 'BELEN',
            '15_090': 'BERBEO',
            '15_092': 'BETEITIVA',
            '15_097': 'BOAVITA',
            '15_104': 'BOYACA',
            '15_106': 'BRICEÑO',
            '15_109': 'BUENAVISTA',
            '15_114': 'BUSBANZA',
            '15_131': 'CALDAS',
            '15_135': 'CAMPOHERMOSO',
            '15_162': 'CERINZA',
            '15_172': 'CHINAVITA',
            '15_176': 'CHIQUINQUIRA',
            '15_180': 'CHISCAS',
            '15_183': 'CHITA',
            '15_185': 'CHITARAQUE',
            '15_187': 'CHIVATA',
            '15_189': 'CIENEGA',
            '15_204': 'COMBITA',
            '15_212': 'COPER',
            '15_215': 'CORRALES',
            '15_218': 'COVARACHIA',
            '15_223': 'CUBARA',
            '15_224': 'CUCAITA',
            '15_226': 'CUITIVA',
            '15_232': 'CHIQUIZA',
            '15_236': 'CHIVOR',
            '15_238': 'DUITAMA',
            '15_244': 'EL COCUY',
            '15_248': 'EL ESPINO',
            '15_272': 'FIRAVITOBA',
            '15_276': 'FLORESTA',
            '15_293': 'GACHANTIVA',
            '15_296': 'GAMEZA',
            '15_299': 'GARAGOA',
            '15_317': 'GUACAMAYAS',
            '15_322': 'GUATEQUE',
            '15_325': 'GUAYATA',
            '15_332': 'GsICAN',
            '15_362': 'IZA',
            '15_367': 'JENESANO',
            '15_368': 'JERICO',
            '15_377': 'LABRANZAGRANDE',
            '15_380': 'LA CAPILLA',
            '15_401': 'LA VICTORIA',
            '15_403': 'LA UVITA',
            '15_407': 'VILLA DE LEYVA',
            '15_425': 'MACANAL',
            '15_442': 'MARIPI',
            '15_455': 'MIRAFLORES',
            '15_464': 'MONGUA',
            '15_466': 'MONGUI',
            '15_469': 'MONIQUIRA',
            '15_476': 'MOTAVITA',
            '15_480': 'MUZO',
            '15_491': 'NOBSA',
            '15_494': 'NUEVO COLON',
            '15_500': 'OICATA',
            '15_507': 'OTANCHE',
            '15_511': 'PACHAVITA',
            '15_514': 'PAEZ',
            '15_516': 'PAIPA',
            '15_518': 'PAJARITO',
            '15_522': 'PANQUEBA',
            '15_531': 'PAUNA',
            '15_533': 'PAYA',
            '15_537': 'PAZ DE RIO',
            '15_542': 'PESCA',
            '15_550': 'PISBA',
            '15_572': 'PUERTO BOYACA',
            '15_580': 'QUIPAMA',
            '15_599': 'RAMIRIQUI',
            '15_600': 'RAQUIRA',
            '15_621': 'RONDON',
            '15_632': 'SABOYA',
            '15_638': 'SACHICA',
            '15_646': 'SAMACA',
            '15_660': 'SAN EDUARDO',
            '15_664': 'SAN JOSE DE PARE',
            '15_667': 'SAN LUIS DE GACENO',
            '15_673': 'SAN MATEO',
            '15_676': 'SAN MIGUEL DE SEMA',
            '15_681': 'SAN PABLO DE BORBUR',
            '15_686': 'SANTANA',
            '15_690': 'SANTA MARIA',
            '15_693': 'SANTA ROSA DE VITERBO',
            '15_696': 'SANTA SOFIA',
            '15_720': 'SATIVANORTE',
            '15_723': 'SATIVASUR',
            '15_740': 'SIACHOQUE',
            '15_753': 'SOATA',
            '15_755': 'SOCOTA',
            '15_757': 'SOCHA',
            '15_759': 'SOGAMOSO',
            '15_761': 'SOMONDOCO',
            '15_762': 'SORA',
            '15_763': 'SOTAQUIRA',
            '15_764': 'SORACA',
            '15_774': 'SUSACON',
            '15_776': 'SUTAMARCHAN',
            '15_778': 'SUTATENZA',
            '15_790': 'TASCO',
            '15_798': 'TENZA',
            '15_804': 'TIBANA',
            '15_806': 'TIBASOSA',
            '15_808': 'TINJACA',
            '15_810': 'TIPACOQUE',
            '15_814': 'TOCA',
            '15_816': 'TOGsI',
            '15_820': 'TOPAGA',
            '15_822': 'TOTA',
            '15_832': 'TUNUNGUA',
            '15_835': 'TURMEQUE',
            '15_837': 'TUTA',
            '15_839': 'TUTAZA',
            '15_842': 'UMBITA',
            '15_861': 'VENTAQUEMADA',
            '15_879': 'VIRACACHA',
            '15_897': 'ZETAQUIRA',
            '17_001': 'MANIZALES',
            '17_013': 'AGUADAS',
            '17_042': 'ANSERMA',
            '17_050': 'ARANZAZU',
            '17_088': 'BELALCAZAR',
            '17_174': 'CHINCHINA',
            '17_272': 'FILADELFIA',
            '17_380': 'LA DORADA',
            '17_388': 'LA MERCED',
            '17_433': 'MANZANARES',
            '17_442': 'MARMATO',
            '17_444': 'MARQUETALIA',
            '17_446': 'MARULANDA',
            '17_486': 'NEIRA',
            '17_495': 'NORCASIA',
            '17_513': 'PACORA',
            '17_524': 'PALESTINA',
            '17_541': 'PENSILVANIA',
            '17_614': 'RIOSUCIO',
            '17_616': 'RISARALDA',
            '17_653': 'SALAMINA',
            '17_662': 'SAMANA',
            '17_665': 'SAN JOSE',
            '17_777': 'SUPIA',
            '17_867': 'VICTORIA',
            '17_873': 'VILLAMARIA',
            '17_877': 'VITERBO',
            '18_001': 'FLORENCIA',
            '18_029': 'ALBANIA',
            '18_094': 'BELEN DE LOS ANDAQUIES',
            '18_150': 'CARTAGENA DEL CHAIRA',
            '18_205': 'CURILLO',
            '18_247': 'EL DONCELLO',
            '18_256': 'EL PAUJIL',
            '18_410': 'LA MONTAÑITA',
            '18_460': 'MILAN',
            '18_479': 'MORELIA',
            '18_592': 'PUERTO RICO',
            '18_610': 'SAN JOSE DEL FRAGUA',
            '18_753': 'SAN VICENTE DEL CAGUAN',
            '18_756': 'SOLANO',
            '18_785': 'SOLITA',
            '18_860': 'VALPARAISO',
            '19_001': 'POPAYAN',
            '19_022': 'ALMAGUER',
            '19_050': 'ARGELIA',
            '19_075': 'BALBOA',
            '19_100': 'BOLIVAR',
            '19_110': 'BUENOS AIRES',
            '19_130': 'CAJIBIO',
            '19_137': 'CALDONO',
            '19_142': 'CALOTO',
            '19_212': 'CORINTO',
            '19_256': 'EL TAMBO',
            '19_290': 'FLORENCIA',
            '19_300': 'GUACHENE',
            '19_318': 'GUAPI',
            '19_355': 'INZA',
            '19_364': 'JAMBALO',
            '19_392': 'LA SIERRA',
            '19_397': 'LA VEGA',
            '19_418': 'LOPEZ',
            '19_450': 'MERCADERES',
            '19_455': 'MIRANDA',
            '19_473': 'MORALES',
            '19_513': 'PADILLA',
            '19_517': 'PAEZ',
            '19_532': 'PATIA',
            '19_533': 'PIAMONTE',
            '19_548': 'PIENDAMO',
            '19_573': 'PUERTO TEJADA',
            '19_585': 'PURACE',
            '19_622': 'ROSAS',
            '19_693': 'SAN SEBASTIAN',
            '19_698': 'SANTANDER DE QUILICHAO',
            '19_701': 'SANTA ROSA',
            '19_743': 'SILVIA',
            '19_760': 'SOTARA',
            '19_780': 'SUAREZ',
            '19_785': 'SUCRE',
            '19_807': 'TIMBIO',
            '19_809': 'TIMBIQUI',
            '19_821': 'TORIBIO',
            '19_824': 'TOTORO',
            '19_845': 'VILLA RICA',
            '20_001': 'VALLEDUPAR',
            '20_011': 'AGUACHICA',
            '20_013': 'AGUSTIN CODAZZI',
            '20_032': 'ASTREA',
            '20_045': 'BECERRIL',
            '20_060': 'BOSCONIA',
            '20_175': 'CHIMICHAGUA',
            '20_178': 'CHIRIGUANA',
            '20_228': 'CURUMANI',
            '20_238': 'EL COPEY',
            '20_250': 'EL PASO',
            '20_295': 'GAMARRA',
            '20_310': 'GONZALEZ',
            '20_383': 'LA GLORIA',
            '20_400': 'LA JAGUA DE IBIRICO',
            '20_443': 'MANAURE',
            '20_517': 'PAILITAS',
            '20_550': 'PELAYA',
            '20_570': 'PUEBLO BELLO',
            '20_614': 'RIO DE ORO',
            '20_621': 'LA PAZ',
            '20_710': 'SAN ALBERTO',
            '20_750': 'SAN DIEGO',
            '20_770': 'SAN MARTIN',
            '20_787': 'TAMALAMEQUE',
            '23_001': 'MONTERIA',
            '23_068': 'AYAPEL',
            '23_079': 'BUENAVISTA',
            '23_090': 'CANALETE',
            '23_162': 'CERETE',
            '23_168': 'CHIMA',
            '23_182': 'CHINU',
            '23_189': 'CIENAGA DE ORO',
            '23_300': 'COTORRA',
            '23_350': 'LA APARTADA',
            '23_417': 'LORICA',
            '23_419': 'LOS CORDOBAS',
            '23_464': 'MOMIL',
            '23_466': 'MONTELIBANO',
            '23_500': 'MOÑITOS',
            '23_555': 'PLANETA RICA',
            '23_570': 'PUEBLO NUEVO',
            '23_574': 'PUERTO ESCONDIDO',
            '23_580': 'PUERTO LIBERTADOR',
            '23_586': 'PURISIMA',
            '23_660': 'SAHAGUN',
            '23_670': 'SAN ANDRES SOTAVENTO',
            '23_672': 'SAN ANTERO',
            '23_675': 'SAN BERNARDO DEL VIENTO',
            '23_678': 'SAN CARLOS',
            '23_686': 'SAN PELAYO',
            '23_807': 'TIERRALTA',
            '23_855': 'VALENCIA',
            '25_001': 'AGUA DE DIOS',
            '25_019': 'ALBAN',
            '25_035': 'ANAPOIMA',
            '25_040': 'ANOLAIMA',
            '25_053': 'ARBELAEZ',
            '25_086': 'BELTRAN',
            '25_095': 'BITUIMA',
            '25_099': 'BOJACA',
            '25_120': 'CABRERA',
            '25_123': 'CACHIPAY',
            '25_126': 'CAJICA',
            '25_148': 'CAPARRAPI',
            '25_151': 'CAQUEZA',
            '25_154': 'CARMEN DE CARUPA',
            '25_168': 'CHAGUANI',
            '25_175': 'CHIA',
            '25_178': 'CHIPAQUE',
            '25_181': 'CHOACHI',
            '25_183': 'CHOCONTA',
            '25_200': 'COGUA',
            '25_214': 'COTA',
            '25_224': 'CUCUNUBA',
            '25_245': 'EL COLEGIO',
            '25_258': 'EL PEÑON',
            '25_260': 'EL ROSAL',
            '25_269': 'FACATATIVA',
            '25_279': 'FOMEQUE',
            '25_281': 'FOSCA',
            '25_286': 'FUNZA',
            '25_288': 'FUQUENE',
            '25_290': 'FUSAGASUGA',
            '25_293': 'GACHALA',
            '25_295': 'GACHANCIPA',
            '25_297': 'GACHETA',
            '25_299': 'GAMA',
            '25_307': 'GIRARDOT',
            '25_312': 'GRANADA',
            '25_317': 'GUACHETA',
            '25_320': 'GUADUAS',
            '25_322': 'GUASCA',
            '25_324': 'GUATAQUI',
            '25_326': 'GUATAVITA',
            '25_328': 'GUAYABAL DE SIQUIMA',
            '25_335': 'GUAYABETAL',
            '25_339': 'GUTIERREZ',
            '25_368': 'JERUSALEN',
            '25_372': 'JUNIN',
            '25_377': 'LA CALERA',
            '25_386': 'LA MESA',
            '25_394': 'LA PALMA',
            '25_398': 'LA PEÑA',
            '25_402': 'LA VEGA',
            '25_407': 'LENGUAZAQUE',
            '25_426': 'MACHETA',
            '25_430': 'MADRID',
            '25_436': 'MANTA',
            '25_438': 'MEDINA',
            '25_473': 'MOSQUERA',
            '25_483': 'NARIÑO',
            '25_486': 'NEMOCON',
            '25_488': 'NILO',
            '25_489': 'NIMAIMA',
            '25_491': 'NOCAIMA',
            '25_506': 'VENECIA',
            '25_513': 'PACHO',
            '25_518': 'PAIME',
            '25_524': 'PANDI',
            '25_530': 'PARATEBUENO',
            '25_535': 'PASCA',
            '25_572': 'PUERTO SALGAR',
            '25_580': 'PULI',
            '25_592': 'QUEBRADANEGRA',
            '25_594': 'QUETAME',
            '25_596': 'QUIPILE',
            '25_599': 'APULO',
            '25_612': 'RICAURTE',
            '25_645': 'SAN ANTONIO DEL TEQUENDAMA',
            '25_649': 'SAN BERNARDO',
            '25_653': 'SAN CAYETANO',
            '25_658': 'SAN FRANCISCO',
            '25_662': 'SAN JUAN DE RIO SECO',
            '25_718': 'SASAIMA',
            '25_736': 'SESQUILE',
            '25_740': 'SIBATE',
            '25_743': 'SILVANIA',
            '25_745': 'SIMIJACA',
            '25_754': 'SOACHA',
            '25_758': 'SOPO',
            '25_769': 'SUBACHOQUE',
            '25_772': 'SUESCA',
            '25_777': 'SUPATA',
            '25_779': 'SUSA',
            '25_781': 'SUTATAUSA',
            '25_785': 'TABIO',
            '25_793': 'TAUSA',
            '25_797': 'TENA',
            '25_799': 'TENJO',
            '25_805': 'TIBACUY',
            '25_807': 'TIBIRITA',
            '25_815': 'TOCAIMA',
            '25_817': 'TOCANCIPA',
            '25_823': 'TOPAIPI',
            '25_839': 'UBALA',
            '25_841': 'UBAQUE',
            '25_843': 'VILLA DE SAN DIEGO DE UBATE',
            '25_845': 'UNE',
            '25_851': 'UTICA',
            '25_862': 'VERGARA',
            '25_867': 'VIANI',
            '25_871': 'VILLAGOMEZ',
            '25_873': 'VILLAPINZON',
            '25_875': 'VILLETA',
            '25_878': 'VIOTA',
            '25_885': 'YACOPI',
            '25_898': 'ZIPACON',
            '25_899': 'ZIPAQUIRA',
            '27_001': 'QUIBDO',
            '27_006': 'ACANDI',
            '27_025': 'ALTO BAUDO',
            '27_050': 'ATRATO',
            '27_073': 'BAGADO',
            '27_075': 'BAHIA SOLANO',
            '27_077': 'BAJO BAUDO',
            '27_099': 'BOJAYA',
            '27_135': 'EL CANTON DEL SAN PABLO',
            '27_150': 'CARMEN DEL DARIEN',
            '27_160': 'CERTEGUI',
            '27_205': 'CONDOTO',
            '27_245': 'EL CARMEN DE ATRATO',
            '27_250': 'EL LITORAL DEL SAN JUAN',
            '27_361': 'ISTMINA',
            '27_372': 'JURADO',
            '27_413': 'LLORO',
            '27_425': 'MEDIO ATRATO',
            '27_430': 'MEDIO BAUDO',
            '27_450': 'MEDIO SAN JUAN',
            '27_491': 'NOVITA',
            '27_495': 'NUQUI',
            '27_580': 'RIO IRO',
            '27_600': 'RIO QUITO',
            '27_615': 'RIOSUCIO',
            '27_660': 'SAN JOSE DEL PALMAR',
            '27_745': 'SIPI',
            '27_787': 'TADO',
            '27_800': 'UNGUIA',
            '27_810': 'UNION PANAMERICANA',
            '41_001': 'NEIVA',
            '41_006': 'ACEVEDO',
            '41_013': 'AGRADO',
            '41_016': 'AIPE',
            '41_020': 'ALGECIRAS',
            '41_026': 'ALTAMIRA',
            '41_078': 'BARAYA',
            '41_132': 'CAMPOALEGRE',
            '41_206': 'COLOMBIA',
            '41_244': 'ELIAS',
            '41_298': 'GARZON',
            '41_306': 'GIGANTE',
            '41_319': 'GUADALUPE',
            '41_349': 'HOBO',
            '41_357': 'IQUIRA',
            '41_359': 'ISNOS',
            '41_378': 'LA ARGENTINA',
            '41_396': 'LA PLATA',
            '41_483': 'NATAGA',
            '41_503': 'OPORAPA',
            '41_518': 'PAICOL',
            '41_524': 'PALERMO',
            '41_530': 'PALESTINA',
            '41_548': 'PITAL',
            '41_551': 'PITALITO',
            '41_615': 'RIVERA',
            '41_660': 'SALADOBLANCO',
            '41_668': 'SAN AGUSTIN',
            '41_676': 'SANTA MARIA',
            '41_770': 'SUAZA',
            '41_791': 'TARQUI',
            '41_797': 'TESALIA',
            '41_799': 'TELLO',
            '41_801': 'TERUEL',
            '41_807': 'TIMANA',
            '41_872': 'VILLAVIEJA',
            '41_885': 'YAGUARA',
            '44_001': 'RIOHACHA',
            '44_035': 'ALBANIA',
            '44_078': 'BARRANCAS',
            '44_090': 'DIBULLA',
            '44_098': 'DISTRACCION',
            '44_110': 'EL MOLINO',
            '44_279': 'FONSECA',
            '44_378': 'HATONUEVO',
            '44_420': 'LA JAGUA DEL PILAR',
            '44_430': 'MAICAO',
            '44_560': 'MANAURE',
            '44_650': 'SAN JUAN DEL CESAR',
            '44_847': 'URIBIA',
            '44_855': 'URUMITA',
            '44_874': 'VILLANUEVA',
            '47_001': 'SANTA MARTA',
            '47_030': 'ALGARROBO',
            '47_053': 'ARACATACA',
            '47_058': 'ARIGUANI',
            '47_161': 'CERRO SAN ANTONIO',
            '47_170': 'CHIBOLO',
            '47_189': 'CIENAGA',
            '47_205': 'CONCORDIA',
            '47_245': 'EL BANCO',
            '47_258': 'EL PIÑON',
            '47_268': 'EL RETEN',
            '47_288': 'FUNDACION',
            '47_318': 'GUAMAL',
            '47_460': 'NUEVA GRANADA',
            '47_541': 'PEDRAZA',
            '47_545': 'PIJIÑO DEL CARMEN',
            '47_551': 'PIVIJAY',
            '47_555': 'PLATO',
            '47_570': 'PUEBLOVIEJO',
            '47_605': 'REMOLINO',
            '47_660': 'SABANAS DE SAN ANGEL',
            '47_675': 'SALAMINA',
            '47_692': 'SAN SEBASTIAN DE BUENAVISTA',
            '47_703': 'SAN ZENON',
            '47_707': 'SANTA ANA',
            '47_720': 'SANTA BARBARA DE PINTO',
            '47_745': 'SITIONUEVO',
            '47_798': 'TENERIFE',
            '47_960': 'ZAPAYAN',
            '47_980': 'ZONA BANANERA',
            '50_001': 'VILLAVICENCIO',
            '50_006': 'ACACIAS',
            '50_110': 'BARRANCA DE UPIA',
            '50_124': 'CABUYARO',
            '50_150': 'CASTILLA LA NUEVA',
            '50_223': 'CUBARRAL',
            '50_226': 'CUMARAL',
            '50_245': 'EL CALVARIO',
            '50_251': 'EL CASTILLO',
            '50_270': 'EL DORADO',
            '50_287': 'FUENTE DE ORO',
            '50_313': 'GRANADA',
            '50_318': 'GUAMAL',
            '50_325': 'MAPIRIPAN',
            '50_330': 'MESETAS',
            '50_350': 'LA MACARENA',
            '50_370': 'URIBE',
            '50_400': 'LEJANIAS',
            '50_450': 'PUERTO CONCORDIA',
            '50_568': 'PUERTO GAITAN',
            '50_573': 'PUERTO LOPEZ',
            '50_577': 'PUERTO LLERAS',
            '50_590': 'PUERTO RICO',
            '50_606': 'RESTREPO',
            '50_680': 'SAN CARLOS DE GUAROA',
            '50_683': 'SAN JUAN DE ARAMA',
            '50_686': 'SAN JUANITO',
            '50_689': 'SAN MARTIN',
            '50_711': 'VISTAHERMOSA',
            '52_001': 'PASTO',
            '52_019': 'ALBAN',
            '52_022': 'ALDANA',
            '52_036': 'ANCUYA',
            '52_051': 'ARBOLEDA',
            '52_079': 'BARBACOAS',
            '52_083': 'BELEN',
            '52_110': 'BUESACO',
            '52_203': 'COLON',
            '52_207': 'CONSACA',
            '52_210': 'CONTADERO',
            '52_215': 'CORDOBA',
            '52_224': 'CUASPUD',
            '52_227': 'CUMBAL',
            '52_233': 'CUMBITARA',
            '52_240': 'CHACHAGsI',
            '52_250': 'EL CHARCO',
            '52_254': 'EL PEÑOL',
            '52_256': 'EL ROSARIO',
            '52_258': 'EL TABLON DE GOMEZ',
            '52_260': 'EL TAMBO',
            '52_287': 'FUNES',
            '52_317': 'GUACHUCAL',
            '52_320': 'GUAITARILLA',
            '52_323': 'GUALMATAN',
            '52_352': 'ILES',
            '52_354': 'IMUES',
            '52_356': 'IPIALES',
            '52_378': 'LA CRUZ',
            '52_381': 'LA FLORIDA',
            '52_385': 'LA LLANADA',
            '52_390': 'LA TOLA',
            '52_399': 'LA UNION',
            '52_405': 'LEIVA',
            '52_411': 'LINARES',
            '52_418': 'LOS ANDES',
            '52_427': 'MAGsI',
            '52_435': 'MALLAMA',
            '52_473': 'MOSQUERA',
            '52_480': 'NARIÑO',
            '52_490': 'OLAYA HERRERA',
            '52_506': 'OSPINA',
            '52_520': 'FRANCISCO PIZARRO',
            '52_540': 'POLICARPA',
            '52_560': 'POTOSI',
            '52_565': 'PROVIDENCIA',
            '52_573': 'PUERRES',
            '52_585': 'PUPIALES',
            '52_612': 'RICAURTE',
            '52_621': 'ROBERTO PAYAN',
            '52_678': 'SAMANIEGO',
            '52_683': 'SANDONA',
            '52_685': 'SAN BERNARDO',
            '52_687': 'SAN LORENZO',
            '52_693': 'SAN PABLO',
            '52_694': 'SAN PEDRO DE CARTAGO',
            '52_696': 'SANTA BARBARA',
            '52_699': 'SANTACRUZ',
            '52_720': 'SAPUYES',
            '52_786': 'TAMINANGO',
            '52_788': 'TANGUA',
            '52_835': 'SAN ANDRES DE TUMACO',
            '52_838': 'TUQUERRES',
            '52_885': 'YACUANQUER',
            '54_001': 'CUCUTA',
            '54_003': 'ABREGO',
            '54_051': 'ARBOLEDAS',
            '54_099': 'BOCHALEMA',
            '54_109': 'BUCARASICA',
            '54_125': 'CACOTA',
            '54_128': 'CACHIRA',
            '54_172': 'CHINACOTA',
            '54_174': 'CHITAGA',
            '54_206': 'CONVENCION',
            '54_223': 'CUCUTILLA',
            '54_239': 'DURANIA',
            '54_245': 'EL CARMEN',
            '54_250': 'EL TARRA',
            '54_261': 'EL ZULIA',
            '54_313': 'GRAMALOTE',
            '54_344': 'HACARI',
            '54_347': 'HERRAN',
            '54_377': 'LABATECA',
            '54_385': 'LA ESPERANZA',
            '54_398': 'LA PLAYA',
            '54_405': 'LOS PATIOS',
            '54_418': 'LOURDES',
            '54_480': 'MUTISCUA',
            '54_498': 'OCAÑA',
            '54_518': 'PAMPLONA',
            '54_520': 'PAMPLONITA',
            '54_553': 'PUERTO SANTANDER',
            '54_599': 'RAGONVALIA',
            '54_660': 'SALAZAR',
            '54_670': 'SAN CALIXTO',
            '54_673': 'SAN CAYETANO',
            '54_680': 'SANTIAGO',
            '54_720': 'SARDINATA',
            '54_743': 'SILOS',
            '54_800': 'TEORAMA',
            '54_810': 'TIBU',
            '54_820': 'TOLEDO',
            '54_871': 'VILLA CARO',
            '54_874': 'VILLA DEL ROSARIO',
            '63_001': 'ARMENIA',
            '63_111': 'BUENAVISTA',
            '63_130': 'CALARCA',
            '63_190': 'CIRCASIA',
            '63_212': 'CORDOBA',
            '63_272': 'FILANDIA',
            '63_302': 'GENOVA',
            '63_401': 'LA TEBAIDA',
            '63_470': 'MONTENEGRO',
            '63_548': 'PIJAO',
            '63_594': 'QUIMBAYA',
            '63_690': 'SALENTO',
            '66_001': 'PEREIRA',
            '66_045': 'APIA',
            '66_075': 'BALBOA',
            '66_088': 'BELEN DE UMBRIA',
            '66_170': 'DOSQUEBRADAS',
            '66_318': 'GUATICA',
            '66_383': 'LA CELIA',
            '66_400': 'LA VIRGINIA',
            '66_440': 'MARSELLA',
            '66_456': 'MISTRATO',
            '66_572': 'PUEBLO RICO',
            '66_594': 'QUINCHIA',
            '66_682': 'SANTA ROSA DE CABAL',
            '66_687': 'SANTUARIO',
            '68_001': 'BUCARAMANGA',
            '68_013': 'AGUADA',
            '68_020': 'ALBANIA',
            '68_051': 'ARATOCA',
            '68_077': 'BARBOSA',
            '68_079': 'BARICHARA',
            '68_081': 'BARRANCABERMEJA',
            '68_092': 'BETULIA',
            '68_101': 'BOLIVAR',
            '68_121': 'CABRERA',
            '68_132': 'CALIFORNIA',
            '68_147': 'CAPITANEJO',
            '68_152': 'CARCASI',
            '68_160': 'CEPITA',
            '68_162': 'CERRITO',
            '68_167': 'CHARALA',
            '68_169': 'CHARTA',
            '68_176': 'CHIMA',
            '68_179': 'CHIPATA',
            '68_190': 'CIMITARRA',
            '68_207': 'CONCEPCION',
            '68_209': 'CONFINES',
            '68_211': 'CONTRATACION',
            '68_217': 'COROMORO',
            '68_229': 'CURITI',
            '68_235': 'EL CARMEN DE CHUCURI',
            '68_245': 'EL GUACAMAYO',
            '68_250': 'EL PEÑON',
            '68_255': 'EL PLAYON',
            '68_264': 'ENCINO',
            '68_266': 'ENCISO',
            '68_271': 'FLORIAN',
            '68_276': 'FLORIDABLANCA',
            '68_296': 'GALAN',
            '68_298': 'GAMBITA',
            '68_307': 'GIRON',
            '68_318': 'GUACA',
            '68_320': 'GUADALUPE',
            '68_322': 'GUAPOTA',
            '68_324': 'GUAVATA',
            '68_327': 'GsEPSA',
            '68_344': 'HATO',
            '68_368': 'JESUS MARIA',
            '68_370': 'JORDAN',
            '68_377': 'LA BELLEZA',
            '68_385': 'LANDAZURI',
            '68_397': 'LA PAZ',
            '68_406': 'LEBRIJA',
            '68_418': 'LOS SANTOS',
            '68_425': 'MACARAVITA',
            '68_432': 'MALAGA',
            '68_444': 'MATANZA',
            '68_464': 'MOGOTES',
            '68_468': 'MOLAGAVITA',
            '68_498': 'OCAMONTE',
            '68_500': 'OIBA',
            '68_502': 'ONZAGA',
            '68_522': 'PALMAR',
            '68_524': 'PALMAS DEL SOCORRO',
            '68_533': 'PARAMO',
            '68_547': 'PIEDECUESTA',
            '68_549': 'PINCHOTE',
            '68_572': 'PUENTE NACIONAL',
            '68_573': 'PUERTO PARRA',
            '68_575': 'PUERTO WILCHES',
            '68_615': 'RIONEGRO',
            '68_655': 'SABANA DE TORRES',
            '68_669': 'SAN ANDRES',
            '68_673': 'SAN BENITO',
            '68_679': 'SAN GIL',
            '68_682': 'SAN JOAQUIN',
            '68_684': 'SAN JOSE DE MIRANDA',
            '68_686': 'SAN MIGUEL',
            '68_689': 'SAN VICENTE DE CHUCURI',
            '68_705': 'SANTA BARBARA',
            '68_720': 'SANTA HELENA DEL OPON',
            '68_745': 'SIMACOTA',
            '68_755': 'SOCORRO',
            '68_770': 'SUAITA',
            '68_773': 'SUCRE',
            '68_780': 'SURATA',
            '68_820': 'TONA',
            '68_855': 'VALLE DE SAN JOSE',
            '68_861': 'VELEZ',
            '68_867': 'VETAS',
            '68_872': 'VILLANUEVA',
            '68_895': 'ZAPATOCA',
            '70_001': 'SINCELEJO',
            '70_110': 'BUENAVISTA',
            '70_124': 'CAIMITO',
            '70_204': 'COLOSO',
            '70_215': 'COROZAL',
            '70_221': 'COVEÑAS',
            '70_230': 'CHALAN',
            '70_233': 'EL ROBLE',
            '70_235': 'GALERAS',
            '70_265': 'GUARANDA',
            '70_400': 'LA UNION',
            '70_418': 'LOS PALMITOS',
            '70_429': 'MAJAGUAL',
            '70_473': 'MORROA',
            '70_508': 'OVEJAS',
            '70_523': 'PALMITO',
            '70_670': 'SAMPUES',
            '70_678': 'SAN BENITO ABAD',
            '70_702': 'SAN JUAN DE BETULIA',
            '70_708': 'SAN MARCOS',
            '70_713': 'SAN ONOFRE',
            '70_717': 'SAN PEDRO',
            '70_742': 'SAN LUIS DE SINCE',
            '70_771': 'SUCRE',
            '70_820': 'SANTIAGO DE TOLU',
            '70_823': 'TOLU VIEJO',
            '73_001': 'IBAGUE',
            '73_024': 'ALPUJARRA',
            '73_026': 'ALVARADO',
            '73_030': 'AMBALEMA',
            '73_043': 'ANZOATEGUI',
            '73_055': 'ARMERO',
            '73_067': 'ATACO',
            '73_124': 'CAJAMARCA',
            '73_148': 'CARMEN DE APICALA',
            '73_152': 'CASABIANCA',
            '73_168': 'CHAPARRAL',
            '73_200': 'COELLO',
            '73_217': 'COYAIMA',
            '73_226': 'CUNDAY',
            '73_236': 'DOLORES',
            '73_268': 'ESPINAL',
            '73_270': 'FALAN',
            '73_275': 'FLANDES',
            '73_283': 'FRESNO',
            '73_319': 'GUAMO',
            '73_347': 'HERVEO',
            '73_349': 'HONDA',
            '73_352': 'ICONONZO',
            '73_408': 'LERIDA',
            '73_411': 'LIBANO',
            '73_443': 'MARIQUITA',
            '73_449': 'MELGAR',
            '73_461': 'MURILLO',
            '73_483': 'NATAGAIMA',
            '73_504': 'ORTEGA',
            '73_520': 'PALOCABILDO',
            '73_547': 'PIEDRAS',
            '73_555': 'PLANADAS',
            '73_563': 'PRADO',
            '73_585': 'PURIFICACION',
            '73_616': 'RIOBLANCO',
            '73_622': 'RONCESVALLES',
            '73_624': 'ROVIRA',
            '73_671': 'SALDAÑA',
            '73_675': 'SAN ANTONIO',
            '73_678': 'SAN LUIS',
            '73_686': 'SANTA ISABEL',
            '73_770': 'SUAREZ',
            '73_854': 'VALLE DE SAN JUAN',
            '73_861': 'VENADILLO',
            '73_870': 'VILLAHERMOSA',
            '73_873': 'VILLARRICA',
            '76_001': 'CALI',
            '76_020': 'ALCALA',
            '76_036': 'ANDALUCIA',
            '76_041': 'ANSERMANUEVO',
            '76_054': 'ARGELIA',
            '76_100': 'BOLIVAR',
            '76_109': 'BUENAVENTURA',
            '76_111': 'GUADALAJARA DE BUGA',
            '76_113': 'BUGALAGRANDE',
            '76_122': 'CAICEDONIA',
            '76_126': 'CALIMA',
            '76_130': 'CANDELARIA',
            '76_147': 'CARTAGO',
            '76_233': 'DAGUA',
            '76_243': 'EL AGUILA',
            '76_246': 'EL CAIRO',
            '76_248': 'EL CERRITO',
            '76_250': 'EL DOVIO',
            '76_275': 'FLORIDA',
            '76_306': 'GINEBRA',
            '76_318': 'GUACARI',
            '76_364': 'JAMUNDI',
            '76_377': 'LA CUMBRE',
            '76_400': 'LA UNION',
            '76_403': 'LA VICTORIA',
            '76_497': 'OBANDO',
            '76_520': 'PALMIRA',
            '76_563': 'PRADERA',
            '76_606': 'RESTREPO',
            '76_616': 'RIOFRIO',
            '76_622': 'ROLDANILLO',
            '76_670': 'SAN PEDRO',
            '76_736': 'SEVILLA',
            '76_823': 'TORO',
            '76_828': 'TRUJILLO',
            '76_834': 'TULUA',
            '76_845': 'ULLOA',
            '76_863': 'VERSALLES',
            '76_869': 'VIJES',
            '76_890': 'YOTOCO',
            '76_892': 'YUMBO',
            '76_895': 'ZARZAL',
            '81_001': 'ARAUCA',
            '81_065': 'ARAUQUITA',
            '81_220': 'CRAVO NORTE',
            '81_300': 'FORTUL',
            '81_591': 'PUERTO RONDON',
            '81_736': 'SARAVENA',
            '81_794': 'TAME',
            '85_001': 'YOPAL',
            '85_010': 'AGUAZUL',
            '85_015': 'CHAMEZA',
            '85_125': 'HATO COROZAL',
            '85_136': 'LA SALINA',
            '85_139': 'MANI',
            '85_162': 'MONTERREY',
            '85_225': 'NUNCHIA',
            '85_230': 'OROCUE',
            '85_250': 'PAZ DE ARIPORO',
            '85_263': 'PORE',
            '85_279': 'RECETOR',
            '85_300': 'SABANALARGA',
            '85_315': 'SACAMA',
            '85_325': 'SAN LUIS DE PALENQUE',
            '85_400': 'TAMARA',
            '85_410': 'TAURAMENA',
            '85_430': 'TRINIDAD',
            '85_440': 'VILLANUEVA',
            '86_001': 'MOCOA',
            '86_219': 'COLON',
            '86_320': 'ORITO',
            '86_568': 'PUERTO ASIS',
            '86_569': 'PUERTO CAICEDO',
            '86_571': 'PUERTO GUZMAN',
            '86_573': 'LEGUIZAMO',
            '86_749': 'SIBUNDOY',
            '86_755': 'SAN FRANCISCO',
            '86_757': 'SAN MIGUEL',
            '86_760': 'SANTIAGO',
            '86_865': 'VALLE DEL GUAMUEZ',
            '86_885': 'VILLAGARZON',
            '88_001': 'SAN ANDRES',
            '88_564': 'PROVIDENCIA',
            '91_001': 'LETICIA',
            '91_263': 'EL ENCANTO',
            '91_405': 'LA CHORRERA',
            '91_407': 'LA PEDRERA',
            '91_430': 'LA VICTORIA',
            '91_460': 'MIRITI - PARANA',
            '91_530': 'PUERTO ALEGRIA',
            '91_536': 'PUERTO ARICA',
            '91_540': 'PUERTO NARIÑO',
            '91_669': 'PUERTO SANTANDER',
            '91_798': 'TARAPACA',
            '94_001': 'INIRIDA',
            '94_343': 'BARRANCO MINAS',
            '94_663': 'MAPIRIPANA',
            '94_883': 'SAN FELIPE',
            '94_884': 'PUERTO COLOMBIA',
            '94_885': 'LA GUADALUPE',
            '94_886': 'CACAHUAL',
            '94_887': 'PANA PANA',
            '94_888': 'MORICHAL',
            '95_001': 'SAN JOSE DEL GUAVIARE',
            '95_015': 'CALAMAR',
            '95_025': 'EL RETORNO',
            '95_200': 'MIRAFLORES',
            '97_001': 'MITU',
            '97_161': 'CARURU',
            '97_511': 'PACOA',
            '97_666': 'TARAIRA',
            '97_777': 'PAPUNAUA',
            '97_889': 'YAVARATE',
            '99_001': 'PUERTO CARREÑO',
            '99_524': 'LA PRIMAVERA',
            '99_624': 'SANTA ROSALIA',

        },
        "barrios": [
            { "barrios": "ANTIOQUIA" },
            { "barrios": "ATLANTICO" },
            { "barrios": "BOGOTA" },
            { "barrios": "BOLIVAR" },
            { "barrios": "BOYACA" },
            { "barrios": "CALDAS" },
            { "barrios": "CAQUETA" },
            { "barrios": "CAUCA" },
            { "barrios": "CESAR" },
            { "barrios": "CORDOBA" },
            { "barrios": "CUNDINAMARCA" },
            { "barrios": "CHOCO" },
            { "barrios": "HUILA" },
            { "barrios": "LA GUAJIRA" },
            { "barrios": "MAGDALENA" },
            { "barrios": "META" },
            { "barrios": "NARIÑO" },
            { "barrios": "N. DE SANTANDER" },
            { "barrios": "QUINDIO" },
            { "barrios": "RISARALDA" },
            { "barrios": "SANTANDER" },
            { "barrios": "SUCRE" },
            { "barrios": "TOLIMA" },
            { "barrios": "VALLE DEL CAUCA" },
            { "barrios": "ARAUCA" },
            { "barrios": "CASANARE" },
            { "barrios": "PUTUMAYO" },
            { "barrios": "SAN ANDRES" },
            { "barrios": "AMAZONAS" },
            { "barrios": "GUAINIA" },
            { "barrios": "GUAVIARE" },
            { "barrios": "VAUPES" },
            { "barrios": "VICHADA" },
        ],
        "cities": {
            "ANTIOQUIA": [
                "MEDELLIN",
                "ABEJORRAL",
                "ABRIAQUI",
                "ALEJANDRIA",
                "AMAGA",
                "AMALFI",
                "ANDES",
                "ANGELOPOLIS",
                "ANGOSTURA",
                "ANORI",
                "SANTAFE DE ANTIOQUIA",
                "ANZA",
                "APARTADO",
                "ARBOLETES",
                "ARGELIA",
                "ARMENIA",
                "BARBOSA",
                "BELMIRA",
                "BELLO",
                "BETANIA",
                "BETULIA",
                "CIUDAD BOLIVAR",
                "BRICEÑO",
                "BURITICA",
                "CACERES",
                "CAICEDO",
                "CALDAS",
                "CAMPAMENTO",
                "CAÑASGORDAS",
                "CARACOLI",
                "CARAMANTA",
                "CAREPA",
                "EL CARMEN DE VIBORAL",
                "CAROLINA",
                "CAUCASIA",
                "CHIGORODO",
                "CISNEROS",
                "COCORNA",
                "CONCEPCION",
                "CONCORDIA",
                "COPACABANA",
                "DABEIBA",
                "DON MATIAS",
                "EBEJICO",
                "EL_BAGRE",
                "ENTRERRIOS",
                "ENVIGADO",
                "FREDONIA",
                "FRONTINO",
                "GIRALDO",
                "GIRARDOTA",
                "GOMEZ_PLATA",
                "GRANADA",
                "GUADALUPE",
                "GUARNE",
                "GUATAPE",
                "HELICONIA",
                "HISPANIA",
                "ITAGUI",
                "ITUANGO",
                "JARDIN",
                "JERICO",
                "LA CEJA",
                "LA ESTRELLA",
                "LA PINTADA",
                "LA UNION",
                "LIBORINA",
                "MACEO",
                "MARINILLA",
                "MONTEBELLO",
                "MURINDO",
                "MUTATA",
                "NARIÑO",
                "NECOCLI",
                "NECHI",
                "OLAYA",
                "PEDOL",
                "PEQUE",
                "PUEBLORRICO",
                "PUERTO BERRIO",
                "PUERTO NARE",
                "PUERTO TRIUNFO",
                "REMEDIOS",
                "RETIRO",
                "RIONEGRO",
                "SABANALARGA",
                "SABANETA",
                "SALGAR",
                "SAN ANDRES DE CUERQUIA",
                "SAN CARLOS",
                "SAN FRANCISCO",
                "SAN JERONIMO",
                "SAN JOSE DE LA MONTAÑA",
                "SAN JUAN DE URABA",
                "SAN LUIS",
                "SAN PEDRO",
                "SAN PEDRO DE URABA",
                "SAN RAFAEL",
                "SAN ROQUE",
                "SAN VICENTE",
                "SAN BARBARA",
                "SANTA ROSA DE OSOS",
                "SANTO DOMINGO",
                "EL SANTUARIO",
                "SEGOVIA",
                "SONSON",
                "SOPETRAN",
                "TAMESIS",
                "TARAZA",
                "TARSO",
                "TITIRIBI",
                "TOLEDO",
                "TURBO",
                "URAMITA",
                "URRAO",
                "VALDIVIA",
                "VALPARAISO",
                "VEGACHI",
                "VENECIA",
                "VIGIA DEL FUERTE",
                "YALI",
                "YARUMAL",
                "YOLOMBO",
                "YONDO",
                "ZARAGOZA"
            ],
            "ATLANTICO": [
                "BARRANQUILLA",
                "BARANOA",
                "CAMPO DE LA CRUZ",
                "CANDELARIA",
                "GALAPA",
                "JUAN DE ACOSTA",
                "LURUACO",
                "MALAMBO",
                "MANATI",
                "PALMAR DE VARELA",
                "PIOJO",
                "POLONUEVO",
                "PONEDERA",
                "PUERTO COLOMBIA",
                "REPELON",
                "SABANAGRANDE",
                "SABANALARGA",
                "SANTA LUCIA",
                "SANTO TOMAS",
                "SOLEDAD",
                "SUAN",
                "TUBARA",
                "USIACURI"
            ],
            "BOGOTA": [
                "BOGOTA, D.C."
            ],
            "BOLIVAR": [
                "CARTAGENA",
                "ACHI",
                "ALTOS DEL ROSARIO",
                "ARENAL",
                "ARJONA",
                "ARROYOHONDO",
                "BARRANCO DE LOBA",
                "CALAMAR",
                "CANTAGALLO",
                "CICUCO",
                "CORDOBA",
                "CLEMENCIA",
                "EL CARMEN DE BOLIVAR",
                "EL GUAMO",
                "EL PEÑON",
                "HATILLO DE LOBA",
                "MAGANGUE",
                "MAHATES",
                "MARGARITA",
                "MARIA LA BAJA",
                "MONTECRISTO",
                "MOMPOS",
                "NOROSI",
                "MORALES",
                "PINILLOS",
                "REGIDOR",
                "RIO VIEJO",
                "SAN CRISTOBAL",
                "SAN ESTANISLAO",
                "SAN FERNANDO",
                "SAN JACINTO",
                "SAN JACINTO DEL CAUCA",
                "SAN JUAN NEPOMUCENO",
                "SAN MARTIN DE LOBA",
                "SAN PABLO",
                "SANTA CATALINA",
                "SANTA ROSA",
                "SANTA ROSA DEL SUR",
                "SIMITI",
                "SOPLAVIENTO",
                "TALAIGUA NUEVO",
                "TIQUISIO",
                "TURBACO",
                "TURBANA",
                "VILLANUEVA",
                "ZAMBRANO"
            ],
            "BOYACA": [
                "TUNJA",
                "ALMEIDA",
                "AQUITANIA",
                "ARCABUCO",
                "BELEN",
                "BERBEO",
                "BETEITIVA",
                "BOAVITA",
                "BOYACA",
                "BRICEÑO",
                "BUENAVISTA",
                "BUSBANZA",
                "CALDAS",
                "CAMPOHERMOSO",
                "CERINZA",
                "CHINAVITA",
                "CHIQUINQUIRA",
                "CHISCAS",
                "CHITA",
                "CHITARAQUE",
                "CHIVATA",
                "CIENEGA",
                "COMBITA",
                "COPER",
                "CORRALES",
                "COVARACHIA",
                "CUBARA",
                "CUCAITA",
                "CUITIVA",
                "CHIQUIZA",
                "CHIVOR",
                "DUITAMA",
                "EL COCUY",
                "EL ESPINO",
                "FIRAVITOBA",
                "FLORESTA",
                "GACHANTIVA",
                "GAMEZA",
                "GARAGOA",
                "GUACAMAYAS",
                "GUATEQUE",
                "GUAYATA",
                "GsICAN",
                "IZA",
                "JENESANO",
                "JERICO",
                "LABRANZAGRANDE",
                "LA CAPILLA",
                "LA VICTORIA",
                "LA UVITA",
                "VILLA DE LEYVA",
                "MACANAL",
                "MARIPI",
                "MIRAFLORES",
                "MONGUA",
                "MONGUI",
                "MONIQUIRA",
                "MOTAVITA",
                "MUZO",
                "NOBSA",
                "NUEVO COLON",
                "OICATA",
                "OTANCHE",
                "PACHAVITA",
                "PAEZ",
                "PAIPA",
                "PAJARITO",
                "PANQUEBA",
                "PAUNA",
                "PAYA",
                "PAZ DE RIO",
                "PESCA",
                "PISBA",
                "PUERTO BOYACA",
                "QUIPAMA",
                "RAMIRIQUI",
                "RAQUIRA",
                "RONDON",
                "SABOYA",
                "SACHICA",
                "SAMACA",
                "SAN EDUARDO",
                "SAN JOSE DE PARE",
                "SAN LUIS DE GACENO",
                "SAN MATEO",
                "SAN MIGUEL DE SEMA",
                "SAN PABLO DE BORBUR",
                "SANTANA",
                "SANTA MARIA",
                "SANTA ROSA DE VITERBO",
                "SANTA SOFIA",
                "SATIVANORTE",
                "SATIVASUR",
                "SIACHOQUE",
                "SOATA",
                "SOCOTA",
                "SOCHA",
                "SOGAMOSO",
                "SOMONDOCO",
                "SORA",
                "SOTAQUIRA",
                "SORACA",
                "SUSACON",
                "SUTAMARCHAN",
                "SUTATENZA",
                "TASCO",
                "TENZA",
                "TIBANA",
                "TIBASOSA",
                "TINJACA",
                "TIPACOQUE",
                "TOCA",
                "TOGsI",
                "TOPAGA",
                "TOTA",
                "TUNUNGUA",
                "TURMEQUE",
                "TUTA",
                "TUTAZA",
                "UMBITA",
                "VENTAQUEMADA",
                "VIRACACHA",
                "ZETAQUIRA",
            ],
            "CALDAS": [
                "AGUADAS",
                "ANSERMA",
                "ARANZAZU",
                "BELALCAZAR",
                "CHINCHINA",
                "FILADELFIA",
                "LA DORADA",
                "LA MERCED",
                "MANZANARES",
                "MARMATO",
                "MARQUETALIA",
                "MARULANDA",
                "NEIRA",
                "NORCASIA",
                "PACORA",
                "PALESTINA",
                "PENSILVANIA",
                "RIOSUCIO",
                "RISARALDA",
                "SALAMINA",
                "SAMANA",
                "SAN JOSE",
                "SUPIA",
                "VICTORIA",
                "VILLAMARIA",
                "VITERBO",
            ],
            "CAQUETA": [
                "FLORENCIA",
                "ALBANIA",
                "BELEN DE LOS ANDAQUIES",
                "CARTAGENA DEL CHAIRA",
                "CURILLO",
                "EL DONCELLO",
                "EL PAUJIL",
                "LA MONTAÑITA",
                "MILAN",
                "MORELIA",
                "PUERTO RICO",
                "SAN JOSE DEL FRAGUA",
                "SAN VICENTE DEL CAGUAN",
                "SOLANO",
                "SOLITA",
                "VALPARAISO",
            ],
            "CAUCA": [
                "POPAYAN",
                "ALMAGUER",
                "ARGELIA",
                "BALBOA",
                "BOLIVAR",
                "BUENOS AIRES",
                "CAJIBIO",
                "CALDONO",
                "CALOTO",
                "CORINTO",
                "EL TAMBO",
                "FLORENCIA",
                "GUACHENE",
                "GUAPI",
                "INZA",
                "JAMBALO",
                "LA SIERRA",
                "LA VEGA",
                "LOPEZ",
                "MERCADERES",
                "MIRANDA",
                "MORALES",
                "PADILLA",
                "PAEZ",
                "PATIA",
                "PIAMONTE",
                "PIENDAMO",
                "PUERTO TEJADA",
                "PURACE",
                "ROSAS",
                "SAN SEBASTIAN",
                "SANTANDER DE QUILICHAO",
                "SANTA ROSA",
                "SILVIA",
                "SOTARA",
                "SUAREZ",
                "SUCRE",
                "TIMBIO",
                "TIMBIQUI",
                "TORIBIO",
                "TOTORO",
                "VILLA RICA",
            ],
            "CESAR": [
                "VALLEDUPAR",
                "AGUACHICA",
                "AGUSTIN CODAZZI",
                "ASTREA",
                "BECERRIL",
                "BOSCONIA",
                "CHIMICHAGUA",
                "CHIRIGUANA",
                "CURUMANI",
                "EL COPEY",
                "EL PASO",
                "GAMARRA",
                "GONZALEZ",
                "LA GLORIA",
                "LA JAGUA DE IBIRICO",
                "MANAURE",
                "PAILITAS",
                "PELAYA",
                "PUEBLO BELLO",
                "RIO DE ORO",
                "LA PAZ",
                "SAN ALBERTO",
                "SAN DIEGO",
                "SAN MARTIN",
            ],
            "CORDOBA": [
                "MONTERIA",
                "AYAPEL",
                "BUENAVISTA",
                "CANALETE",
                "CERETE",
                "CHIMA",
                "CHINU",
                "CIENAGA DE ORO",
                "COTORRA",
                "LA APARTADA",
                "LORICA",
                "LOS CORDOBAS",
                "MOMIL",
                "MONTELIBANO",
                "MOÑITOS",
                "PLANETA RICA",
                "PUEBLO NUEVO",
                "PUERTO ESCONDIDO",
                "PUERTO LIBERTADOR",
                "PURISIMA",
                "SAHAGUN",
                "SAN ANDRES SOTAVENTO",
                "SAN ANTERO",
                "SAN BERNARDO DEL VIENTO",
                "SAN CARLOS",
                "SAN PELAYO",
                "TIERRALTA",
                "VALENCIA",
            ],
            "CUNDINAMARCA": [
                "AGUA DE DIOS",
                "ALBAN",
                "ANAPOIMA",
                "ANOLAIMA",
                "ARBELAEZ",
                "BELTRAN",
                "BITUIMA",
                "BOJACA",
                "CABRERA",
                "CACHIPAY",
                "CAJICA",
                "CAPARRAPI",
                "CAQUEZA",
                "CARMEN DE CARUPA",
                "CHAGUANI",
                "CHIA",
                "CHIPAQUE",
                "CHOACHI",
                "CHOCONTA",
                "COGUA",
                "COTA",
                "CUCUNUBA",
                "EL COLEGIO",
                "EL PEÑON",
                "EL ROSAL",
                "FACATATIVA",
                "FOMEQUE",
                "FOSCA",
                "FUNZA",
                "FUQUENE",
                "FUSAGASUGA",
                "GACHALA",
                "GACHANCIPA",
                "GACHETA",
                "GAMA",
                "GIRARDOT",
                "GRANADA",
                "GUACHETA",
                "GUADUAS",
                "GUASCA",
                "GUATAQUI",
                "GUATAVITA",
                "GUAYABAL DE SIQUIMA",
                "GUAYABETAL",
                "GUTIERREZ",
                "JERUSALEN",
                "JUNIN",
                "LA CALERA",
                "LA MESA",
                "LA PALMA",
                "LA PEÑA",
                "LA VEGA",
                "LENGUAZAQUE",
                "MACHETA",
                "MADRID",
                "MANTA",
                "MEDINA",
                "MOSQUERA",
                "NARIÑO",
                "NEMOCON",
                "NILO",
                "NIMAIMA",
                "NOCAIMA",
                "VENECIA",
                "PACHO",
                "PAIME",
                "PANDI",
                "PARATEBUENO",
                "PASCA",
                "PUERTO SALGAR",
                "PULI",
                "QUEBRADANEGRA",
                "QUETAME",
                "QUIPILE",
                "APULO",
                "RICAURTE",
                "SAN ANTONIO DEL TEQUENDAMA",
                "SAN BERNARDO",
                "SAN CAYETANO",
                "SAN FRANCISCO",
                "SAN JUAN DE RIO SECO",
                "SASAIMA",
                "SESQUILE",
                "SIBATE",
                "SILVANIA",
                "SIMIJACA",
                "SOACHA",
                "SOPO",
                "SUBACHOQUE",
                "SUESCA",
                "SUPATA",
                "SUSA",
                "SUTATAUSA",
                "TABIO",
                "TAUSA",
                "TENA",
                "TENJO",
                "TIBACUY",
                "TIBIRITA",
                "TOCAIMA",
                "TOCANCIPA",
                "TOPAIPI",
                "UBALA",
                "UBAQUE",
                "VILLA DE SAN DIEGO DE UBATE",
                "UNE",
                "UTICA",
                "VERGARA",
                "VIANI",
                "VILLAGOMEZ",
                "VILLAPINZON",
                "VILLETA",
                "VIOTA",
                "YACOPI",
                "ZIPACON",
                "ZIPAQUIRA",
            ],
            "CHOCO": [
                "QUIBDO",
                "ACANDI",
                "ALTO BAUDO",
                "ATRATO",
                "BAGADO",
                "BAHIA SOLANO",
                "BAJO BAUDO",
                "BOJAYA",
                "EL CANTON DEL SAN PABLO",
                "CARMEN DEL DARIEN",
                "CERTEGUI",
                "CONDOTO",
                "EL CARMEN DE ATRATO",
                "EL LITORAL DEL SAN JUAN",
                "ISTMINA",
                "JURADO",
                "LLORO",
                "MEDIO ATRATO",
                "MEDIO BAUDO",
                "MEDIO SAN JUAN",
                "NOVITA",
                "NUQUI",
                "RIO IRO",
                "RIO QUITO",
                "RIOSUCIO",
                "SAN JOSE DEL PALMAR",
                "SIPI",
                "TADO",
                "UNGUIA",
                "UNION PANAMERICANA",
            ],
            "HUILA": [
                "NEIVA",
                "ACEVEDO",
                "AGRADO",
                "AIPE",
                "ALGECIRAS",
                "ALTAMIRA",
                "BARAYA",
                "CAMPOALEGRE",
                "COLOMBIA",
                "ELIAS",
                "GARZON",
                "GIGANTE",
                "GUADALUPE",
                "HOBO",
                "IQUIRA",
                "ISNOS",
                "LA ARGENTINA",
                "LA PLATA",
                "NATAGA",
                "OPORAPA",
                "PAICOL",
                "PALERMO",
                "PALESTINA",
                "PITAL",
                "PITALITO",
                "RIVERA",
                "SALADOBLANCO",
                "SAN AGUSTIN",
                "TESALIA",
                "TELLO",
                "TERUEL",
                "TIMANA",
                "VILLAVIEJA",
                "YAGUARA",
            ],
            "LA GUAJIRA": [
                "RIOHACHA",
                "ALBANIA",
                "BARRANCAS",
                "DIBULLA",
                "DISTRACCION",
                "EL MOLINO",
                "FONSECA",
                "HATONUEVO",
                "LA JAGUA DEL PILAR",
                "MAICAO",
                "MANAURE",
                "SAN JUAN DEL CESAR",
                "URIBIA",
                "URUMITA",
                "VILLANUEVA",
            ],
            "MAGDALENA": [
                "SANTA MARTA",
                "ALGARROBO",
                "ARACATACA",
                "ARIGUANI",
                "CERRO SAN ANTONIO",
                "CHIBOLO",
                "CIENAGA",
                "CONCORDIA",
                "EL BANCO",
                "EL PIÑON",
                "EL RETEN",
                "FUNDACION",
                "GUAMAL",
                "NUEVA GRANADA",
                "PEDRAZA",
                "PIJIÑO DEL CARMEN",
                "PIVIJAY",
                "PLATO",
                "PUEBLOVIEJO",
                "REMOLINO",
                "SABANAS DE SAN ANGEL",
                "SALAMINA",
                "SAN SEBASTIAN DE BUENAVISTA",
                "SAN ZENON",
                "SANTA ANA",
                "SANTA BARBARA DE PINTO",
                "SITIONUEVO",
                "TENERIFE",
                "ZAPAYAN",
                "ZONA BANANERA",
            ],
            "META": [
                "VILLAVICENCIO",
                "ACACIAS",
                "BARRANCA DE UPIA",
                "CABUYARO",
                "CASTILLA LA NUEVA",
                "CUBARRAL",
                "CUMARAL",
                "EL CALVARIO",
                "EL CASTILLO",
                "EL DORADO",
                "FUENTE DE ORO",
                "GRANADA",
                "GUAMAL",
                "MAPIRIPAN",
                "MESETAS",
                "LA MACARENA",
                "URIBE",
                "LEJANIAS",
                "PUERTO CONCORDIA",
                "PUERTO GAITAN",
                "PUERTO LOPEZ",
                "PUERTO LLERAS",
                "PUERTO RICO",
                "RESTREPO",
                "SAN CARLOS DE GUAROA",
                "SAN JUAN DE ARAMA",
                "SAN JUANITO",
                "SAN MARTIN",
                "VISTAHERMOSA",
            ],
            "NARIÑO": [
                "PASTO",
                "ALBAN",
                "ALDANA",
                "ANCUYA",
                "ARBOLEDA",
                "BARBACOAS",
                "BELEN",
                "BUESACO",
                "COLON",
                "CONSACA",
                "CONTADERO",
                "CORDOBA",
                "CUASPUD",
                "CUMBAL",
                "CUMBITARA",
                "CHACHAGsI",
                "EL CHARCO",
                "EL PEÑOL",
                "EL ROSARIO",
                "EL TABLON DE GOMEZ",
                "EL TAMBO",
                "FUNES",
                "GUACHUCAL",
                "GUAITARILLA",
                "GUALMATAN",
                "ILES",
                "IMUES",
                "IPIALES",
                "LA CRUZ",
                "LA FLORIDA",
                "LA LLANADA",
                "LA TOLA",
                "LA UNION",
                "LEIVA",
                "LINARES",
                "LOS ANDES",
                "MAGsI",
                "MALLAMA",
                "MOSQUERA",
                "NARIÑO",
                "OLAYA HERRERA",
                "PUERRES",
                "PUPIALES",
                "RICAURTE",
                "ROBERTO PAYAN",
                "SAMANIEGO",
                "SANDONA",
                "SAN PEDRO DE CARTAGO",
                "SANTA BARBARA",
                "SANTACRUZ",
                "SAPUYES",
                "TAMINANGO",
                "TANGUA",
                "SAN ANDRES DE TUMACO",
            ],
            "N. DE SANTANDER": [
                "CUCUTA",
                "ABREGO",
                "ARBOLEDAS",
                "BOCHALEMA",
                "BUCARASICA",
                "CACOTA",
                "CACHIRA",
                "CHINACOTA",
                "CHITAGA",
                "CONVENCION",
                "CUCUTILLA",
                "DURANIA",
                "EL CARMEN",
                "EL TARRA",
                "EL ZULIA",
                "GRAMALOTE",
                "HACARI",
                "HERRAN",
                "LABATECA",
                "LA ESPERANZA",
                "LA PLAYA",
                "LOS PATIOS",
                "LOURDES",
                "MUTISCUA",
                "OCAÑA",
                "PAMPLONA",
                "PAMPLONITA",
                "PUERTO SANTANDER",
                "RAGONVALIA",
                "SALAZAR",
                "SAN CALIXTO",
                "SAN CAYETANO",
                "SANTIAGO",
                "SARDINATA",
                "SILOS",
                "TEORAMA",
                "TIBU",
                "TOLEDO",
                "VILLA CARO",
                "VILLA DEL ROSARIO",
            ],
            "QUINDIO": [
                "ARMENIA",
                "BUENAVISTA",
                "CALARCA",
                "CIRCASIA",
                "CORDOBA",
                "FILANDIA",
                "GENOVA",
                "LA TEBAIDA",
                "MONTENEGRO",
                "PIJAO",
                "QUIMBAYA",
                "SALENTO",
            ],
            "RISARALDA": [
                "PEREIRA",
                "APIA",
                "BALBOA",
                "BELEN DE UMBRIA",
                "DOSQUEBRADAS",
                "GUATICA",
                "LA CELIA",
                "LA VIRGINIA",
                "MARSELLA",
                "MISTRATO",
                "PUEBLO RICO",
                "QUINCHIA",
                "SANTA ROSA DE CABAL",
                "SANTUARIO",
            ],
            "SANTANDER": [
                "BUCARAMANGA",
                "AGUADA",
                "ALBANIA",
                "ARATOCA",
                "BARBOSA",
                "BARICHARA",
                "BARRANCABERMEJA",
                "BETULIA",
                "BOLIVAR",
                "CABRERA",
                "CALIFORNIA",
                "CAPITANEJO",
                "CARCASI",
                "CEPITA",
                "CERRITO",
                "CHARALA",
                "CHARTA",
                "CHIMA",
                "CHIPATA",
                "CIMITARRA",
                "CONCEPCION",
                "CONFINES",
                "CONTRATACION",
                "COROMORO",
                "CURITI",
                "EL CARMEN DE CHUCURI",
                "EL GUACAMAYO",
                "EL PEÑON",
                "EL PLAYON",
                "ENCINO",
                "ENCISO",
                "FLORIAN",
                "FLORIDABLANCA",
                "GALAN",
                "GAMBITA",
                "GIRON",
                "GUACA",
                "GUADALUPE",
                "GUAPOTA",
                "GUAVATA",
                "GsEPSA",
                "HATO",
                "JESUS MARIA",
                "JORDAN",
                "LA BELLEZA",
                "LANDAZURI",
                "LA PAZ",
                "LEBRIJA",
                "LOS SANTOS",
                "MACARAVITA",
                "MALAGA",
                "MATANZA",
                "MOGOTES",
                "MOLAGAVITA",
                "OCAMONTE",
                "OIBA",
                "ONZAGA",
                "PALMAR",
                "PALMAS DEL SOCORRO",
                "PARAMO",
                "PIEDECUESTA",
                "PINCHOTE",
                "PUENTE NACIONAL",
                "PUERTO PARRA",
                "PUERTO WILCHES",
                "RIONEGRO",
                "SABANA DE TORRES",
                "SAN ANDRES",
                "SAN BENITO",
                "SAN GIL",
                "SAN JOAQUIN",
                "SAN JOSE DE MIRANDA",
                "SAN MIGUEL",
                "SAN VICENTE DE CHUCURI",
                "SANTA BARBARA",
                "SANTA HELENA DEL OPON",
                "SIMACOTA",
                "SOCORRO",
                "SUAITA",
                "SUCRE",
                "SURATA",
                "TONA",
                "VALLE DE SAN JOSE",
                "VELEZ",
                "VETAS",
                "VILLANUEVA",
                "ZAPATOCA",
            ],
            "SUCRE": [
                "SINCELEJO",
                "BUENAVISTA",
                "CAIMITO",
                "COLOSO",
                "COROZAL",
                "COVEÑAS",
                "CHALAN",
                "EL ROBLE",
                "GALERAS",
                "GUARANDA",
                "LA UNION",
                "LOS PALMITOS",
                "MAJAGUAL",
                "MORROA",
                "OVEJAS",
                "PALMITO",
                "SAMPUES",
                "SAN BENITO ABAD",
                "SAN JUAN DE BETULIA",
                "SAN MARCOS",
                "SAN ONOFRE",
                "SAN PEDRO",
                "SAN LUIS DE SINCE",
                "SUCRE",
                "SANTIAGO DE TOLU",
                "TOLU VIEJO",
            ],
            "TOLIMA": [
                "IBAGUE",
                "ALPUJARRA",
                "ALVARADO",
                "AMBALEMA",
                "ANZOATEGUI",
                "ARMERO",
                "ATACO",
                "CAJAMARCA",
                "CARMEN DE APICALA",
                "CASABIANCA",
                "CHAPARRAL",
                "COELLO",
                "COYAIMA",
                "CUNDAY",
                "DOLORES",
                "ESPINAL",
                "FALAN",
                "FLANDES",
                "FRESNO",
                "GUAMO",
                "HERVEO",
                "HONDA",
                "ICONONZO",
                "LERIDA",
                "LIBANO",
                "MARIQUITA",
                "MELGAR",
                "MURILLO",
                "NATAGAIMA",
                "ORTEGA",
                "PALOCABILDO",
                "PIEDRAS",
                "PLANADAS",
                "PRADO",
                "PURIFICACION",
                "RIOBLANCO",
                "RONCESVALLES",
                "ROVIRA",
                "SALDAÑA",
                "SAN ANTONIO",
                "SAN LUIS",
                "SANTA ISABEL",
                "SUAREZ",
                "VALLE DE SAN JUAN",
                "VENADILLO",
                "VILLAHERMOSA",
                "VILLARRICA",
            ],
            "VALLE DEL CAUCA": [
                "CALI",
                "ALCALA",
                "ANDALUCIA",
                "ANSERMANUEVO",
                "ARGELIA",
                "BOLIVAR",
                "BUENAVENTURA",
                "GUADALAJARA DE BUGA",
                "BUGALAGRANDE",
                "CAICEDONIA",
                "CALIMA",
                "CANDELARIA",
                "CARTAGO",
                "DAGUA",
                "EL AGUILA",
                "EL CAIRO",
                "EL CERRITO",
                "EL DOVIO",
                "FLORIDA",
                "GINEBRA",
                "GUACARI",
                "JAMUNDI",
                "LA CUMBRE",
                "LA UNION",
                "LA VICTORIA",
                "OBANDO",
                "PALMIRA",
                "PRADERA",
                "RESTREPO",
                "RIOFRIO",
                "ROLDANILLO",
                "SAN PEDRO",
                "SEVILLA",
                "TORO",
                "TRUJILLO",
                "TULUA",
                "ULLOA",
                "VERSALLES",
                "VIJES",
                "YOTOCO",
                "YUMBO",
                "ZARZAL",
            ],
            "ARAUCA": [
                "ARAUCA",
                "ARAUQUITA",
                "CRAVO NORTE",
                "FORTUL",
                "PUERTO RONDON",
                "SARAVENA",
                "TAME",
            ],
            "CASANARE": [
                "YOPAL",
                "AGUAZUL",
                "CHAMEZA",
                "HATO COROZAL",
                "LA SALINA",
                "MANI",
                "MONTERREY",
                "NUNCHIA",
                "OROCUE",
                "PAZ DE ARIPORO",
                "PORE",
                "RECETOR",
                "SABANALARGA",
                "SACAMA",
                "SAN LUIS DE PALENQUE",
                "TAMARA",
                "TAURAMENA",
                "TRINIDAD",
                "VILLANUEVA",
            ],
            "PUTUMAYO": [
                "MOCOA",
                "COLON",
                "ORITO",
                "PUERTO ASIS",
                "PUERTO CAICEDO",
                "PUERTO GUZMAN",
                "LEGUIZAMO",
                "SIBUNDOY",
                "SAN FRANCISCO",
                "SAN MIGUEL",
                "SANTIAGO",
                "VALLE DEL GUAMUEZ",
                "VILLAGARZON",
            ],
            "SAN ANDRES": [
                "SAN ANDRES",
                "PROVIDENCIA",
            ],
            "AMAZONAS": [
                "LETICIA",
                "EL ENCANTO",
                "LA CHORRERA",
                "LA PEDRERA",
                "LA VICTORIA",
                "MIRITI - PARANA",
                "PUERTO ALEGRIA",
                "PUERTO ARICA",
                "PUERTO NARIÑO",
                "PUERTO SANTANDER",
                "TARAPACA",
            ],
            "GUAINIA": [
                "INIRIDA",
                "BARRANCO MINAS",
                "MAPIRIPANA",
                "SAN FELIPE",
                "PUERTO COLOMBIA",
                "LA GUADALUPE",
                "CACAHUAL",
                "PANA PANA",
                "MORICHAL",
            ],
            "GUAVIARE": [
                "SAN JOSE DEL GUAVIARE",
                "CALAMAR",
                "EL RETORNO",
                "MIRAFLORES",
            ],
            "VAUPES": [
                "MITU",
                "CARURU",
                "PACOA",
                "TARAIRA",
                "PAPUNAUA",
                "YAVARATE",
            ],
            "VICHADA": [
                "PUERTO CARREÑO",
                "LA PRIMAVERA",
                "SANTA ROSALIA",
                "CUMARIBO",
            ]

        }

    }
}